services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin@123
      MONGO_INITDB_DATABASE: major_project_db
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - major_project_network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-compass
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin@123
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin%40123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin@123
    depends_on:
      - mongodb
    networks:
      - major_project_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      cache_from:
        - major_project_clg-backend:latest
    image: major_project_clg-backend:latest
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      FLASK_ENV: production
      MONGODB_URI: mongodb://admin:admin%40123@mongodb:27017/major_project_db?authSource=admin
      FLASK_APP: app_mongodb.py
    depends_on:
      - mongodb
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    networks:
      - major_project_network

volumes:
  mongodb_data:
  mongodb_config:

networks:
  major_project_network:
    driver: bridge
